// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/battle-redesign/Disciplined.tsx": () => import("../components/mockups/battle-redesign/Disciplined.tsx"),
  "./components/mockups/battle-redesign/Holographic.tsx": () => import("../components/mockups/battle-redesign/Holographic.tsx"),
  "./components/mockups/battle-redesign/Neon.tsx": () => import("../components/mockups/battle-redesign/Neon.tsx"),
  "./components/mockups/battle-redesign/Segmented.tsx": () => import("../components/mockups/battle-redesign/Segmented.tsx")
};
