// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/battle-redesign/Current.tsx": () => import("../components/mockups/battle-redesign/Current.tsx"),
  "./components/mockups/battle-redesign/Disciplined.tsx": () => import("../components/mockups/battle-redesign/Disciplined.tsx"),
  "./components/mockups/battle-redesign/ModeAware.tsx": () => import("../components/mockups/battle-redesign/ModeAware.tsx")
};
